# -*- coding: utf-8 -*-
"""mllab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EBssl6RP6uT4gE5mSJHYVMGJcEpTtWoi
"""



import pandas as pd
import numpy as np

def load_purchase_data(file_path):
    return pd.read_excel(file_path, sheet_name='Purchase Data')

def segregate_matrices(data):
    A = data[['Month', 'Day', 'Price', 'Open', 'High', 'Low', 'Volume', 'Chg%']].values
    C = data[['Date']].values
    return A, C

def vector_space_dimensionality(matrix_A):
    return matrix_A.shape[1]

def number_of_vectors(matrix_A):
    return matrix_A.shape[0]

def matrix_rank(matrix_A):
    return np.linalg.matrix_rank(matrix_A)

def calculate_product_costs(matrix_A, matrix_C):
    pseudo_inverse_A = np.linalg.pinv(matrix_A)
    product_costs = pseudo_inverse_A @ matrix_C
    return product_costs

file_path = "Lab Session1 Data.xlsx"
data = load_purchase_data(file_path)
matrix_A, matrix_C = segregate_matrices(data)

dimensionality = vector_space_dimensionality(matrix_A)
num_vectors = number_of_vectors(matrix_A)
rank_A = matrix_rank(matrix_A)
product_costs = calculate_product_costs(matrix_A, matrix_C)

print("Dimensionality of the vector space:", dimensionality)
print("Number of vectors in the vector space:", num_vectors)
print("Rank of Matrix A:", rank_A)
print("Cost of each product:", product_costs)